### ISSUE TITLE
Suggestion: Show CPS

### ISSUE THREAD

**Issue by Craanky** [Khronophobia/Inputs-Viewer#2]
Show CPS on the keys

**Comment by Khronophobia** [comment]
Added as of v1.1.0

**Comment by Craanky** [comment]
> Added as of v1.1.0

Thanks, but currently, it updates only once per second. It should continuously display the number of clicks made in the last second. For example, if you click once, the count increases by 1. If you click again after 500ms, the count becomes 2. However, after another 500ms, the first click is removed from the count since it has been 1 second since that click.
