### ISSUE TITLE
Suggestion: Change how CPS calculation works

### ISSUE THREAD

**Issue by Craanky** [Khronophobia/Inputs-Viewer#6]
Currently, it updates only once per second. It should continuously display the number of clicks made in the last second. For example, if you click once, the count increases by 1. If you click again after 500ms, the count becomes 2. However, after another 500ms, the first click is removed from the count since it has been 1 second since that click.

**Comment by Khronophobia** [comment]
Added as of v1.2.0. Set `CPS Calculation` in mod settings to `Real-Time` (should be the default)
